config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from government.core.views import home

urlpatterns = [
    path("",
         home,
         name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("government.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("members/", include("government.members.urls", namespace="member")),
    path("areas/", include("government.areas.urls", namespace="area")),
    # path(
    #     "lords/",
    #     include("government.lords.urls", namespace="lords"),
    # ),
    # path(
    #     "structure/",
    #     include("government.structure.urls", namespace="structure"),
    # )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

government/areas/urls.py
from django.urls import path

from .views import (
    constituency_list_view,
    constituency_redirect_view,
    constituency_update_view,
    constituency_detail_view,
)

app_name = "constituency"

urlpatterns = [
    path("", view=constituency_list_view, name="list"),
    path("~redirect/", view=constituency_redirect_view, name="redirect"),
    path("~update/", view=constituency_update_view, name="update"),
    path("<slug:slug>/", view=constituency_detail_view, name="detail"),
]

government/members/urls.py
from django.urls import path

from government.members.views import (
    member_list_view,
    member_redirect_view,
    member_update_view,
    member_detail_view,
    cabinet_view
)

app_name = "members"
urlpatterns = [
    path("", view=member_list_view, name="list"),
    path("cabinet/", view=cabinet_view, name="cabinet"),
    path("~redirect/", view=member_redirect_view, name="redirect"),
    path("~update/", view=member_update_view, name="update"),
    path("<slug:slug>/", view=member_detail_view, name="detail"),
]

government/users/urls.py
from django.urls import path

from government.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

government/areas/models.py
from autoslug import AutoSlugField

from django.db import models
from django.db.models import CharField, Model, DateField, ForeignKey, CASCADE
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class County(Model):
    name = CharField(_("Name of county"), blank=True, max_length=255)
    date_of_creation = DateField(_("Date of Birth"), blank=True)

    def get_absolute_url(self):
        return reverse("county:detail", kwargs={"name": self.username})


class Constituency(Model):
    name = CharField(_("Name of Constituency"), blank=True, max_length=255)
    constituency_id = models.IntegerField(_("Government assigned constituency id"))
    constituency_type = CharField(_("Type of constituency"), blank=True, max_length=255, null=True)
    ended_date = DateField(_("Date of removal"), blank=True, null=True)
    previous_constituency = CharField(_("Old Constituency name"), max_length=255, null=True)
    date_of_creation = DateField(_("Date of Creation"), blank=True, null=True)
    slug = AutoSlugField(populate_from='name', unique="true")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("constituency:detail", kwargs={"name": self.username})


class City(Model):
    name = CharField(_("Name of county"), blank=True, max_length=255)
    date_of_creation = DateField(_("Date of Birth"), blank=True)

    def get_absolute_url(self):
        return reverse("city:detail", kwargs={"name": self.username})


class Country(Model):
    name = CharField(_("Name of county"), blank=True, max_length=255)
    capital = ForeignKey(City, on_delete=CASCADE)

    def get_absolute_url(self):
        return reverse("country:detail", kwargs={"name": self.username})

government/groups/models.py
from django.db.models import CharField, Model, DateField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class Party(Model):
    name = CharField(_("The name of the party"), max_length=255)
    created_at = DateField(_("Date of the parties inception"), blank=True)

    def get_absolute_url(self):
        return reverse("party:detail", kwargs={"name": self.name})


class Faction():
    name = CharField(
        _("The generally accepted name of a parliamentary faction"),
        blank=True,
        max_length=255)

    def get_absolute_url(self):
        return reverse("faction:detail", kwargs={"name": self.name})

government/members/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from autoslug import AutoSlugField

from django.utils.text import slugify


class Person(models.Model):
    name = models.CharField(_("Name of Person"), blank=True, max_length=255)
    dob = models.DateField(_("Date of Birth"), blank=True, null=True)
    family_name = models.CharField(_("Surname"), blank=True, max_length=255)
    given_name = models.CharField(_("First Name"), blank=True, max_length=255)
    website = models.CharField(_("Website"), blank=True, max_length=255, null=True)
    twitter = models.CharField(_("Twitter"), blank=True, max_length=255, null=True)
    gender = models.CharField(max_length=10, default="")
    party = models.ForeignKey("Party", default=None, on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from='name', unique="true")
    # faction = ManyToManyField("groups.Faction")

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name


class Member(models.Model):
    constituency = models.ForeignKey(
        "areas.Constituency", on_delete=models.CASCADE)
    cabinet = models.BooleanField(default=False)
    member_from = models.DateField(_("Date of first election"), default=None, null=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, default=None)
    slug = AutoSlugField(populate_from="__str__", unique="true")
    
    def __str__(self):
        return self.person.name

    def party(self):
        return self.person.party.name

    def get_absolute_url(self):
        return reverse("members:detail", kwargs={"username": self.slug})


class Lord(models.Model):
    title = models.CharField(_("Name of Person"), blank=True, max_length=255)
    hereditary = models.BooleanField(default=False)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, default=None)

    def get_absolute_url(self):
        return reverse("lords:detail", kwargs={"username": self.username})


class Vote(models.Model):
    date = models.DateField(_("Date of vote"))
    results = models.ManyToManyField(Member, related_name="vote")


class Election(Vote):
    participants = models.ManyToManyField(Member, related_name="election")


class House(models.Model):
    name = models.CharField(_("The name of the house"), max_length=255)


class Motion(Vote):
    house = models.ForeignKey(House, models.CASCADE)
    summary = models.TextField(_("A summary of the motion."))

    limit = models.Q(models.Q(app_label='members', model='Member') |
                     models.Q(app_label='members', model='Lord'))
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    sponsor = GenericForeignKey('content_type', 'object_id')


class Party(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

government/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

government/areas/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

government/members/forms.py
from django import forms

from .models import Member


class MemberChangeForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = [
            'member_from']


class MemberCreationForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = ['member_from']

    # def clean_username(self):
    #     name = self.cleaned_data["name"]

    #     try:
    #         Member.objects.get(name=name)
    #     except Member.DoesNotExist:
    #         return name

    #     raise ValidationError(self.error_messages["duplicate_name"])

government/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

government/areas/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from .models import Constituency


class ConstituencyDetailView(DetailView):

    model = Constituency
    slug_url_kwarg = "slug"


constituency_detail_view = ConstituencyDetailView.as_view()


class ConstituencyListView(ListView):

    model = Constituency
    slug_field = "slug"
    slug_url_kwarg = "slug"
    paginate_by = 20
    ordering = "slug"


constituency_list_view = ConstituencyListView.as_view()


class ConstituencyUpdateView(UpdateView):

    model = Constituency
    fields = ["name"]

    def get_success_url(self):
        return reverse("constituency:detail", kwargs={"name": self.request.constituency.name})

    def get_object(self):
        return Constituency.objects.get(name=self.request.constituency.name)


constituency_update_view = ConstituencyUpdateView.as_view()


class ConstituencyRedirectView(RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("constituency:detail", kwargs={"name": self.request.constituency.name})


constituency_redirect_view = ConstituencyRedirectView.as_view()

government/core/views.py
import json
import pygeoip
from urllib.request import urlopen
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "pages/home.html"

    def get(self, request, *args, **kwargs):
        user_ip = request.META["REMOTE_ADDR"]
        get_location_from_ip(user_ip)
        
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        return {}


home = HomeView.as_view()


def get_location_from_ip(user_ip):
    GeoIPDatabase = "/app/government/GeoLiteCity.dat"
    ipData = pygeoip.GeoIP(GeoIPDatabase)
    record = ipData.record_by_name(user_ip)
    # print("The geolocation for IP Address %s is:" % user_ip)
    # print("Accurate Location: %s, %s, %s" % (record["city"], record["region_code"], record["country_name"]))
    # print("General Location: %s" % (record["metro_code"]))

government/members/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from .models import Member, Lord


class MemberDetailView(DetailView):

    model = Member
    slug_url_kwarg = "slug"


member_detail_view = MemberDetailView.as_view()


class MemberListView(ListView):

    model = Member
    slug_field = "slug"
    slug_url_kwarg = "slug"
    paginate_by = 20
    ordering = "slug"


member_list_view = MemberListView.as_view()


class MemberUpdateView(UpdateView):

    model = Member
    fields = ["name"]

    def get_success_url(self):
        return reverse("members:detail", kwargs={"name": self.request.member.name})

    def get_object(self):
        return Member.objects.get(name=self.request.member.name)


member_update_view = MemberUpdateView.as_view()


class MemberRedirectView(RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("members:detail", kwargs={"name": self.request.member.name})


member_redirect_view = MemberRedirectView.as_view()


class LordDetailView(LoginRequiredMixin, DetailView):

    model = Lord
    slug_field = "name"
    slug_url_kwarg = "name"


lord_detail_view = LordDetailView.as_view()


class LordListView(LoginRequiredMixin, ListView):

    model = Lord
    slug_field = "name"
    slug_url_kwarg = "name"


lord_list_view = LordListView.as_view()


class LordUpdateView(LoginRequiredMixin, UpdateView):

    model = Lord
    fields = ["name"]

    def get_success_url(self):
        return reverse("lords:detail", kwargs={"name": self.request.lord.name})

    def get_object(self):
        return Lord.objects.get(name=self.request.lord.name)


lord_update_view = LordUpdateView.as_view()


class LordRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("lords:detail", kwargs={"name": self.request.lord.name})


lord_redirect_view = LordRedirectView.as_view()


class CabinetView(ListView):

    model = Member
    template_name = 'members/cabinet.html'
    context_object_name = 'cabinet'
    queryset = Member.objects.filter(cabinet=True)

cabinet_view = CabinetView.as_view()

government/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

government/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

government/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
    <head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>{% block title %}Know Your Government{% endblock title %}</title>
	<meta nname="description" content="">
	<meta name="author" content="">

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
	<![endif]-->

	<link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

	{% block css %}
	    
	    <!-- Your stuff: Third-party CSS libraries go here -->
	    <!-- Open sans and roboto fonts -->
	    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet"> 

	    <!-- Font awesome icons -->
	    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
	    

	    <!-- This file stores project-specific CSS -->
	    
	    <link href="{% static 'css/project.min.css' %}" rel="stylesheet">
	    
	    
	{% endblock %}

    </head>

    <body>

	<div class="m-b-1">
	    <nav class="navbar navbar-expand-md navbar-light bg-light">
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
			<li class="nav-item active">
			    <a class="nav-link {% block home %}{% endblock %}" href="{% url 'home' %}">Know Your Government</a>
			</li>
			<li class="nav-item">
			    <a class="nav-link {% block members %}{% endblock %}" href="{% url 'members:list' %}">Members</a>
			</li>
			<li class="nav-item">
			    <a class="nav-link {% block cabinet %}{% endblock %}" href="{% url 'members:cabinet' %}">Cabinet</a>
			</li>
			<li class="nav-item">
			    <a class="nav-link {% block about %}{% endblock %}" href="{% url 'about' %}">About</a>
			</li>
		    </ul>
		</div>
	    </nav>
	</div>

	<div class="container">

	    {% if messages %}
		{% for message in messages %}
		    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
		{% endfor %}
	    {% endif %}

	    {% block content %}
	    {% endblock content %}

	</div> <!-- /container -->

	{% block modal %}{% endblock modal %}

	<!-- Le javascript
	     ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	{% block javascript %}
	    
	    <!-- Required by Bootstrap v4.1.1 -->
	    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	    <!-- Your stuff: Third-party javascript libraries go here -->
	    

	    <!-- place project specific Javascript in this file -->
	    
	    <script src="{% static 'js/project.js' %}"></script>
	    

	{% endblock javascript %}
    </body>
</html>

government/templates/user_session_menu_items.html
{% if request.user.is_authenticated %}
			<li class="nav-item">
	{# URL provided by django-allauth/account/urls.py #}
	<a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
    </li>
    <li class="nav-item">
	{# URL provided by django-allauth/account/urls.py #}
	<a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
    </li>
{% else %}
    <li class="nav-item">
	{# URL provided by django-allauth/account/urls.py #}
	<a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
    </li>
    <li class="nav-item">
	{# URL provided by django-allauth/account/urls.py #}
	<a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
    </li>
{% endif %}